<a href="https://colab.research.google.com/github/kchamarty/MachineLearning/blob/master/first.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import data set and convert to dataframe

In [0]:
from sklearn.datasets import load_digits
digits =load_digits()
dg_X=digits.data
dg_y=digits.target

## Split the data into training and test

In [6]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test =train_test_split(dg_X,dg_y,random_state=0)
print('Rows = ',len(X_train))
print('columns = ',len(X_train[0]))

Rows =  1347
columns =  64


In [15]:
# To determine which version you're using:
!pip show tensorflow




Name: tensorflow
Version: 2.0.0
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author: Google Inc.
Author-email: packages@tensorflow.org
License: Apache 2.0
Location: /usr/local/lib/python3.6/dist-packages
Requires: protobuf, tensorboard, termcolor, six, astor, grpcio, absl-py, wrapt, tensorflow-estimator, keras-preprocessing, numpy, wheel, gast, opt-einsum, google-pasta, keras-applications
Required-by: stable-baselines, mesh-tensorflow, magenta, fancyimpute


## importing model and training it

In [0]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors=5)

model.fit(X_train,y_train)
y_pred = model.predict(X_test)

## Results :

In [0]:
from sklearn.metrics import confusion_matrix,accuracy_score
print('Confusion Matrix : \n\n',confusion_matrix(y_pred,y_test))
print('\nAccuracy Score : ',accuracy_score(y_pred,y_test))

Confusion Matrix : 

 [[37  0  0  0  0  0  0  0  0  0]
 [ 0 42  0  0  0  0  0  0  1  0]
 [ 0  0 43  0  0  0  0  0  0  0]
 [ 0  0  1 45  0  0  0  0  1  0]
 [ 0  0  0  0 37  0  0  0  0  0]
 [ 0  1  0  0  0 47  0  0  0  1]
 [ 0  0  0  0  0  0 52  0  1  0]
 [ 0  0  0  0  1  0  0 48  1  0]
 [ 0  0  0  0  0  0  0  0 44  0]
 [ 0  0  0  0  0  1  0  0  0 46]]

Accuracy Score :  0.98
